// Generated by delombok at Wed Oct 02 12:41:06 ART 2019
package tacos;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Pattern;
import org.hibernate.validator.constraints.CreditCardNumber;

public class Order {
    private Long id;
    private Date placedAt;
    @NotBlank(message = "Delivery name is required")
    private String deliveryName;
    @NotBlank(message = "Street is required")
    private String deliveryStreet;
    @NotBlank(message = "City is required")
    private String deliveryCity;
    @NotBlank(message = "State is required")
    private String deliveryState;
    @NotBlank(message = "Zip code is required")
    private String deliveryZip;
    @CreditCardNumber(message = "Not a valid credit card number")
    private String ccNumber;
    @Pattern(regexp = "^(0[1-9]|1[0-2])([\\/])([1-9][0-9])$", message = "Must be formatted MM/YY")
    private String ccExpiration;
    @Digits(integer = 3, fraction = 0, message = "Invalid CVV")
    private String ccCVV;
    private List<Taco> tacos = new ArrayList<>();

    public void addDesign(Taco design) {
        this.tacos.add(design);
    }

    @java.lang.SuppressWarnings("all")
    public Order() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Date getPlacedAt() {
        return this.placedAt;
    }

    @java.lang.SuppressWarnings("all")
    public String getDeliveryName() {
        return this.deliveryName;
    }

    @java.lang.SuppressWarnings("all")
    public String getDeliveryStreet() {
        return this.deliveryStreet;
    }

    @java.lang.SuppressWarnings("all")
    public String getDeliveryCity() {
        return this.deliveryCity;
    }

    @java.lang.SuppressWarnings("all")
    public String getDeliveryState() {
        return this.deliveryState;
    }

    @java.lang.SuppressWarnings("all")
    public String getDeliveryZip() {
        return this.deliveryZip;
    }

    @java.lang.SuppressWarnings("all")
    public String getCcNumber() {
        return this.ccNumber;
    }

    @java.lang.SuppressWarnings("all")
    public String getCcExpiration() {
        return this.ccExpiration;
    }

    @java.lang.SuppressWarnings("all")
    public String getCcCVV() {
        return this.ccCVV;
    }

    @java.lang.SuppressWarnings("all")
    public List<Taco> getTacos() {
        return this.tacos;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlacedAt(final Date placedAt) {
        this.placedAt = placedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setDeliveryName(final String deliveryName) {
        this.deliveryName = deliveryName;
    }

    @java.lang.SuppressWarnings("all")
    public void setDeliveryStreet(final String deliveryStreet) {
        this.deliveryStreet = deliveryStreet;
    }

    @java.lang.SuppressWarnings("all")
    public void setDeliveryCity(final String deliveryCity) {
        this.deliveryCity = deliveryCity;
    }

    @java.lang.SuppressWarnings("all")
    public void setDeliveryState(final String deliveryState) {
        this.deliveryState = deliveryState;
    }

    @java.lang.SuppressWarnings("all")
    public void setDeliveryZip(final String deliveryZip) {
        this.deliveryZip = deliveryZip;
    }

    @java.lang.SuppressWarnings("all")
    public void setCcNumber(final String ccNumber) {
        this.ccNumber = ccNumber;
    }

    @java.lang.SuppressWarnings("all")
    public void setCcExpiration(final String ccExpiration) {
        this.ccExpiration = ccExpiration;
    }

    @java.lang.SuppressWarnings("all")
    public void setCcCVV(final String ccCVV) {
        this.ccCVV = ccCVV;
    }

    @java.lang.SuppressWarnings("all")
    public void setTacos(final List<Taco> tacos) {
        this.tacos = tacos;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Order)) return false;
        final Order other = (Order) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$placedAt = this.getPlacedAt();
        final java.lang.Object other$placedAt = other.getPlacedAt();
        if (this$placedAt == null ? other$placedAt != null : !this$placedAt.equals(other$placedAt)) return false;
        final java.lang.Object this$deliveryName = this.getDeliveryName();
        final java.lang.Object other$deliveryName = other.getDeliveryName();
        if (this$deliveryName == null ? other$deliveryName != null : !this$deliveryName.equals(other$deliveryName)) return false;
        final java.lang.Object this$deliveryStreet = this.getDeliveryStreet();
        final java.lang.Object other$deliveryStreet = other.getDeliveryStreet();
        if (this$deliveryStreet == null ? other$deliveryStreet != null : !this$deliveryStreet.equals(other$deliveryStreet)) return false;
        final java.lang.Object this$deliveryCity = this.getDeliveryCity();
        final java.lang.Object other$deliveryCity = other.getDeliveryCity();
        if (this$deliveryCity == null ? other$deliveryCity != null : !this$deliveryCity.equals(other$deliveryCity)) return false;
        final java.lang.Object this$deliveryState = this.getDeliveryState();
        final java.lang.Object other$deliveryState = other.getDeliveryState();
        if (this$deliveryState == null ? other$deliveryState != null : !this$deliveryState.equals(other$deliveryState)) return false;
        final java.lang.Object this$deliveryZip = this.getDeliveryZip();
        final java.lang.Object other$deliveryZip = other.getDeliveryZip();
        if (this$deliveryZip == null ? other$deliveryZip != null : !this$deliveryZip.equals(other$deliveryZip)) return false;
        final java.lang.Object this$ccNumber = this.getCcNumber();
        final java.lang.Object other$ccNumber = other.getCcNumber();
        if (this$ccNumber == null ? other$ccNumber != null : !this$ccNumber.equals(other$ccNumber)) return false;
        final java.lang.Object this$ccExpiration = this.getCcExpiration();
        final java.lang.Object other$ccExpiration = other.getCcExpiration();
        if (this$ccExpiration == null ? other$ccExpiration != null : !this$ccExpiration.equals(other$ccExpiration)) return false;
        final java.lang.Object this$ccCVV = this.getCcCVV();
        final java.lang.Object other$ccCVV = other.getCcCVV();
        if (this$ccCVV == null ? other$ccCVV != null : !this$ccCVV.equals(other$ccCVV)) return false;
        final java.lang.Object this$tacos = this.getTacos();
        final java.lang.Object other$tacos = other.getTacos();
        if (this$tacos == null ? other$tacos != null : !this$tacos.equals(other$tacos)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Order;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $placedAt = this.getPlacedAt();
        result = result * PRIME + ($placedAt == null ? 43 : $placedAt.hashCode());
        final java.lang.Object $deliveryName = this.getDeliveryName();
        result = result * PRIME + ($deliveryName == null ? 43 : $deliveryName.hashCode());
        final java.lang.Object $deliveryStreet = this.getDeliveryStreet();
        result = result * PRIME + ($deliveryStreet == null ? 43 : $deliveryStreet.hashCode());
        final java.lang.Object $deliveryCity = this.getDeliveryCity();
        result = result * PRIME + ($deliveryCity == null ? 43 : $deliveryCity.hashCode());
        final java.lang.Object $deliveryState = this.getDeliveryState();
        result = result * PRIME + ($deliveryState == null ? 43 : $deliveryState.hashCode());
        final java.lang.Object $deliveryZip = this.getDeliveryZip();
        result = result * PRIME + ($deliveryZip == null ? 43 : $deliveryZip.hashCode());
        final java.lang.Object $ccNumber = this.getCcNumber();
        result = result * PRIME + ($ccNumber == null ? 43 : $ccNumber.hashCode());
        final java.lang.Object $ccExpiration = this.getCcExpiration();
        result = result * PRIME + ($ccExpiration == null ? 43 : $ccExpiration.hashCode());
        final java.lang.Object $ccCVV = this.getCcCVV();
        result = result * PRIME + ($ccCVV == null ? 43 : $ccCVV.hashCode());
        final java.lang.Object $tacos = this.getTacos();
        result = result * PRIME + ($tacos == null ? 43 : $tacos.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Order(id=" + this.getId() + ", placedAt=" + this.getPlacedAt() + ", deliveryName=" + this.getDeliveryName() + ", deliveryStreet=" + this.getDeliveryStreet() + ", deliveryCity=" + this.getDeliveryCity() + ", deliveryState=" + this.getDeliveryState() + ", deliveryZip=" + this.getDeliveryZip() + ", ccNumber=" + this.getCcNumber() + ", ccExpiration=" + this.getCcExpiration() + ", ccCVV=" + this.getCcCVV() + ", tacos=" + this.getTacos() + ")";
    }
}
